### PR TITLE
update parse_server_sdk dependency (fix dependency issue with http)

### PR DESCRIPTION
**Pull request by 2shrestha22**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

## Issue

Closes: n/a

## Tasks

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by mbfakourii** [comment]
Yes, due to the conflict that exists, this possibility is not available until we support Flutter 3.10.
We have to wait until July 2024 for this upgrade ! [[Reference](https://github.com/parse-community/Parse-SDK-Flutter/pull/994#discussion_r1587108197)]

**Comment by mbfakourii** [comment]
> @mbfakourii I believe you mentioned somewhere that we cannot make this upgrade yet, right? Could you please explain...

Yes, due to the conflict that exists, this possibility is not available until we support Flutter 3.10.
We have to wait until July 2024 for this upgrade ! [[Reference](https://github.com/parse-community/Parse-SDK-Flutter/pull/994#discussion_r1587108197)]

**Comment by mtrezza** [comment]
@2shrestha22 What is the issue that this PR is supposed to fix? Could you help us understand the urgency of this?

**Comment by 2shrestha22** [comment]
> @2shrestha22 What is the issue that this PR is supposed to fix? Could you help us understand the urgency of this?

Many packages have already migrated to use http 1.0.0 but parse sdk still depends on old http package and it makes it impossible to add package dependency.

I didn't understand the conflict. How there can be a conflict with flutter framework?

**Comment by mbfakourii** [comment]
> > @2shrestha22 What is the issue that this PR is supposed to fix? Could you help us understand the urgency of this?
> 
> Many packages have already migrated to use http 1.0.0 but parse sdk still depends on old http package and it makes it impossible to add package dependency.
> 
> I didn't understand the conflict. How there can be a conflict with flutter framework?

In Flutter version 3.10, when we go to Parse version 7, we encounter conflicts in some packages.

Check this [PR](https://github.com/parse-community/Parse-SDK-Flutter/pull/994).

**Comment by ebsangam** [comment]
> > > @2shrestha22 What is the issue that this PR is supposed to fix? Could you help us understand the urgency of this?
> > 
> > 
> > Many packages have already migrated to use http 1.0.0 but parse sdk still depends on old http package and it makes it impossible to add package dependency.
> > I didn't understand the conflict. How there can be a conflict with flutter framework?
> 
> In Flutter version 3.10, when we go to Parse version 7, we encounter conflicts in some packages.
> 
> Check this [PR](https://github.com/parse-community/Parse-SDK-Flutter/pull/994) and check [this](https://github.com/parse-community/Parse-SDK-Flutter/actions/runs/8671176221/job/23780068474) fail ci.

We can fix it by updating the Dart SDK constraint in `parse_server_sdk_flutter`. Why waiting?

**Comment by ebsangam** [comment]
Is there any reason we are not updating the Dart SDK constraint to `sdk: ">=3.0.7 <4.0.0"`?

**Comment by mbfakourii** [comment]
> Is there any reason we are not updating the Dart SDK constraint to `sdk: ">=3.0.7 <4.0.0"`?

Please check our [support policy](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#compatibility).

**Comment by mbfakourii** [comment]
> Is there any reason we are not updating the Dart SDK constraint to `sdk: ">=3.0.7 <4.0.0"`?

Please check our Flutter [support policy](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/flutter#compatibility) and Dart [support policy](https://github.com/parse-community/Parse-SDK-Flutter/tree/master/packages/dart#compatibility) .

**Comment by ebsangam** [comment]
That means we are always stuck with old package version? What if developers gets in situation like me and can't use a package due to no support for latest versions? It has been a year since `http v1.0.0` got released and if there is any package that depends on `http v1.0.0` which almost all package will since it has been a year long then we can't use the package. This may not be a good way of handling backward compatibility as Flutter is evolving and in a year there can be lots of changes which will be very difficult to migrate upon if not done gradually.

**Comment by mbfakourii** [comment]
> That means we are always stuck with old package version? What if developers gets in situation like me and can't use a package due to no support for latest versions? It has been a year since `http v1.0.0` got released and if there is any package that depends on `http v1.0.0` which almost all package will since it has been a year long then we can't use the package. This may not be a good way of handling backward compatibility as Flutter is evolving and in a year there can be lots of changes which will be very difficult to migrate upon if not done gradually.

We discussed this a lot before (you can search about it in the repository) and our support policy is currently in this form.
You can use [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) temporarily.

**Comment by ebsangam** [comment]
I don't think dependency override is good thing to do when there are breaking changes.

**Comment by pastordee** [comment]
Since flutter is still evolving, is it possible to change our policy to say every four months for now?

Because I think a year is just too long for us to update the package.

**Comment by mbfakourii** [comment]
Please check [this](https://github.com/parse-community/Parse-SDK-Flutter/issues/872) issues.

**Comment by mtrezza** [comment]
Please everyone feel free to revive the discussion in https://github.com/parse-community/Parse-SDK-Flutter/issues/968 about our support policy and we'll reopen the issue. See the arguments there that have been made to reach the current support policy.

**Comment by 2shrestha22** [comment]
The support policy is not helping developers. Avoiding latest update for old flutter support does look like a good idea. I never seen any packages doing this. May be we need different policy of flutter package.

**Comment by 2shrestha22** [comment]
If you still want to have those policy just remember node and flutter aren't same. Node have lts support but flutter doesn't. Flutter is cutting edge tool. We shouldn't fight with framework.

**Comment by mtrezza** [comment]
We can reopen the discussion in https://github.com/parse-community/Parse-SDK-Flutter/issues/968 if someone wants to respond on the tread there. Please consider the arguments already made there.

**Comment by valerycolong** [comment]
Still having this issue with http: ^0.13. dependency in Sep 2024.

**Comment by mbfakourii** [comment]
upgraded at #1014

**Pull request closed without merging**
