### PR TITLE
ci: Add `fatal-infos` flag to dart and flutter analyze

### PR DESCRIPTION
**Pull request by Nidal-Bakir**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/master/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

## Issue

Closes: https://github.com/parse-community/Parse-SDK-Flutter/issues/905

## Approach

see `fatal-infos` [docs](https://dart.dev/tools/dart-analyze)

### CODE REVIEW

**Comment by Nidal-Bakir** [comment]
Updated the comment

**Comment by mtrezza** [comment]
Great that you found that out and analyzed this so far! I think this is one of the last hurdles since we've been revamping our CI, so we're on a good path.

**Comment by mtrezza** [comment]
Great that you found that out and analyzed this so far! I think this is one of the last hurdles since we've been revamping our CI, so we're on a good path. Maybe @mbfakourii has time to take a look as well.

**Comment by mbfakourii** [comment]
> ### Flutter SDK
> > Run flutter analyze packages/flutter --fatal-infos
> > Analyzing flutter...
> > info • Use 'const' with the constructor to improve performance • packages/flutter/example/lib/live_list/main.dart:52:23 • prefer_const_constructors
> > info • Use 'const' literals as arguments to constructors of '@immutable' classes • packages/flutter/example/lib/live_list/main.dart:54:35 • prefer_const_literals_to_create_immutables
> > info • Use 'const' with the constructor to improve performance • packages/flutter/example/lib/live_list/main.dart:55:2[7](https://github.com/parse-community/Parse-SDK-Flutter/actions/runs/5007799248/jobs/8974884774?pr=906#step:6:8) • prefer_const_constructors
> > info • Use 'const' with the constructor to improve performance • packages/flutter/example/lib/live_list/main.dart:56:27 • prefer_const_constructors
> > 4 issues found. (ran in 15.[9](https://github.com/parse-community/Parse-SDK-Flutter/actions/runs/5007799248/jobs/8974884774?pr=906#step:6:10)s)
> 
> ### Dart SDK
> > Run dart analyze packages/dart --fatal-infos
> > Analyzing dart...
> > info - example\main.dart:1:[8](https://github.com/parse-community/Parse-SDK-Flutter/actions/runs/5007799248/jobs/8974884398?pr=906#step:6:9) - Can't use a relative path to import a library in 'lib'. Try fixing the relative path or changing the import to a 'package:' import. - avoid_relative_lib_imports
> 
> No good. We need to fix this. No wonder the publishing is failing

@Nidal-Bakir Have a good exam ❤️❤️


Regarding the first warnings, I fixed these bugs in the PR, but there was a problem on Flutter 3.3, that's why it was left like this to be supported in this version.

Regarding the second warning, it is better to use it in this way because it is linked to the library in a local form

These are all warnings, I don't think they are the reason for not releasing the version

**Comment by mtrezza** [comment]
> These are all warnings, I don't think they are the reason for not releasing the version

I've added the missing "Issue" reference to the PR description. As you can see there, publishing is failing.

**Comment by mbfakourii** [comment]
> > These are all warnings, I don't think they are the reason for not releasing the version
> 
> I've added the missing "Issue" reference to the PR description. As you can see there, publishing is failing because we are running the analzyer as part of the release workflow with `dart analyze --fatal-infos`. Do you mean we should remove the `fatal-info` and always publish releases regardless of whether they have errors or warnings on the info level?

In this [PR](https://github.com/parse-community/Parse-SDK-Flutter/pull/908), I tried to solve the second warning, probably now we don't have any more publishing problems

**Comment by mtrezza** [comment]
Should these info level warnings prevent a PR from being merged and/or a release from being published?

My concern is that if we don't make them fatal in the CI (what this PR intends) we may miss minor issues when reviewing PRs. But if the issues logged on the info level won't cause any trouble and can be ignored, we may as well not add it to the CI and remove it from the publishing workflow. What do you suggest?

**Comment by mbfakourii** [comment]
> Should such info level warnings prevent a PR from being merged and/or a release from being published? Or can they be ignored for PRs and releases and be solved over time?
> 
> My concern is that if we don't make them fatal in the CI (what this PR intends) we may miss minor issues when reviewing PRs. But if the issues logged on the info level won't cause any trouble and can be ignored, we may as well not add it to the CI and remove it from the publishing workflow. What do you suggest?

In my opinion, we should find out and solve these issues in ci, but these warnings do not cause any problems during the release

**Comment by mtrezza** [comment]
We need to use the same rule for CI and publishing. We can either add the flat or remove it from both. If the flag is not added, anyone is free to look into the CI logs and fix the warnings, but they won't be considered when merging a PR or publishing a release.

**Comment by mtrezza** [comment]
This issue is currently blocking the release pipeline. If there is no contrary opinion I'll remove the flag from all workflows since these are only warnings and merge this PR.

**Comment by Nidal-Bakir** [comment]
I will fix them all give me 30 min

**Comment by Nidal-Bakir** [comment]
#908 
Should fix the Dart SDK I just test it you can merge it and publish the Dart 5.1.1

**Comment by mtrezza** [comment]
So are we sure that we want these warnings to block the merging of PRs and publishing of releases?

**Comment by Nidal-Bakir** [comment]
> So are we sure that we want these warnings to block the merging of PRs

Yes

> and publishing of releases in the future?

If the PR has no warnings or errors, it should not block the publishing process, and the release process should proceed smoothly. The point is if the PR in the first place does not continue any errors we should not counter any errors in the publishing process.

**Comment by mtrezza** [comment]
We don't have a lock file for dependencies, so a PR may show no warnings but the publishing process may indeed, if a dependency has a new release between PR merging and release publishing.

**Comment by Nidal-Bakir** [comment]
This has nothing to do with the dependencies and the lock file. its about the actule code in the SDK

**Comment by mtrezza** [comment]
I assumed the warnings would include any warnings that are caused by dependencies as well. Well, let's merge this.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Pull request merged**
