### PR TITLE
Fix LiveQuery reconnect

### PR DESCRIPTION
**Pull request by FNPCMDs**
Hi! This PR fixes LiveQuery reconnect when internet is disconnected. When _setReconnect() was called, it was not execute a reconnection because !_isConnected returned false.

### CODE REVIEW

**Comment by phillwiggins** [comment]
Great addition. Please can you edit this PR to point at the branch release/1.0.28.

Thanks!

**Comment by FNPCMDs** [comment]
> Great addition. Please can you edit this PR to point at the branch release/1.0.28.
> 
> Thanks!

Sure, give me a minute

**Comment by FNPCMDs** [comment]
> Great addition. Please can you edit this PR to point at the branch release/1.0.28.
> 
> Thanks!

PR fails because there is no `package:flutter_test`. However, I didn't modify pubsec.yaml. Can PR be merged?

**Comment by phillwiggins** [comment]
There seems to be conflicts with this PR. Please can you resolve.

**Comment by FNPCMDs** [comment]
> There seems to be conflicts with this PR. Please can you resolve.

Sure! I'm going to create a new PR, because I need to update my forked version.

**Pull request closed without merging**
