### PR TITLE
refactor: update example app to use Android embedding v2 

### PR DESCRIPTION
**Pull request by fischerscode**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description
Recreated the android application of the flutter example to fix `pub get`.

Related issue: #722 

### Approach
Just recreated...

### TODOs before merging
- [ ] Maybe adjust the title, I had no idea how to name it.

### Expected behavior
The test should fail at the formatting step.

### CODE REVIEW

**Comment by fischerscode** [comment]
@mtrezza 
Just noticed `flutter analyze` treats info level issues as fatal, while `dart analyze` does not. We might want to add `--no-fatal-infos` for now. (Fixing all infos will take some time.)

This is gonna be a problem, I'll research what we can do `warning • Publishable packages can't have 'path' dependencies • packages/flutter/pubspec.yaml:39:5 • invalid_dependency`.
(The flutter package depends on the dart package. In order to test the combination [we use the local path](https://github.com/parse-community/Parse-SDK-Flutter/blob/c9ef6bf1e6056947131fc28216631765124b2bb9/.github/workflows/ci.yml#L55-L56))

**Comment by mtrezza** [comment]
> We might want to add --no-fatal-infos for now.

Sounds good

**Comment by fischerscode** [comment]
> @mtrezza Just noticed `flutter analyze` treats info level issues as fatal, while `dart analyze` does not. We might want to add `--no-fatal-infos` for now. (Fixing all infos will take some time.)
> 
> This is gonna be a problem, I'll research what we can do `warning • Publishable packages can't have 'path' dependencies • packages/flutter/pubspec.yaml:39:5 • invalid_dependency`. (The flutter package depends on the dart package. In order to test the combination [we use the local path](https://github.com/parse-community/Parse-SDK-Flutter/blob/c9ef6bf1e6056947131fc28216631765124b2bb9/.github/workflows/ci.yml#L55-L56))

Keep this to the still missing "Fix analyzer" issue.

**Comment by fischerscode** [comment]
Working on creating the next (maybe last) issue.

**Comment by mtrezza** [comment]
Let me know when this is ready for merge...

**Comment by fischerscode** [comment]
> Let me know when this is ready for merge... do you want to add the `--no-fatal-infos` flag in this PR? It only disregards info logs, but still fails on error, right?

Sorry, missed that comment.

This PR is ready.

We could merge this and then merge master into #731 and see green tests (hopefully) or we could do it the other way round.

I think merging this first is better.

**Comment by mtrezza** [comment]
Alright, let's merge this first then.

**Pull request merged**
