### PR TITLE
refactor: Unsupported platform `web`  in pub.dev

### PR DESCRIPTION
**Pull request by mbfakourii**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/master/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

## Issue
Separation function that is not supported on the web

Closes: #781

## Approach
n/a

## Tasks
n/a

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Review by Nidal-Bakir — APPROVED** [review]

**Comment by mbfakourii** [comment]
@mtrezza I think we don't need to bump the version, I think it is ready for merge

**Comment by Nidal-Bakir** [comment]
> I think we don't need to bump the version

Then how we can see if this PR worked and pub shows the Web support?

---

note: the CI issues have been fixed in this PR #909. So this is ready for merge.

**Comment by mbfakourii** [comment]
> > I think we don't need to bump the version
> 
> Then how we can see if this PR worked and pub shows the Web support?
> 
> note: the CI issues have been fixed in this PR #909. So this is ready for merge.

It is not very important, it can be covered with other pr

**Review by mtrezza — APPROVED** [review]
Looks good, so this is a `refactor`, not a `fix`, correct?

**Comment by mbfakourii** [comment]
> Looks good, so this is a `refactor`, not a `fix`, because web platform was already supported, just pub.dev did not recognize this, correct?

Yes, I don't think there is a need for a new version

**Pull request merged**
