### PR TITLE
Fix CoreStoreSembastImp / Enhancements LiveQuery / New Query Method

### PR DESCRIPTION
**Pull request by RodrigoSMarques**
- Fix CoreStoreSembastImp with no default passwod causes error in Flutter Package
- Makes LiveQuery a class that is not Singleton. This allows you to use more than one LiveQuery at the same time in the app
- Fix ParseACL with no default value in setReadAccess and setWriteAccess
- Add method excludeKeys: Exclude specific fields from the returned query

### CODE REVIEW

**Comment by fischerscode** [comment]
> Makes LiveQuery a class that is not Singleton. This allows you to use more than one LiveQuery at the same time in the app

Could you please explain this to me? From my knowledge, it has been possible to have multiple `LiveQueries` at the same time. Sure, they used the same `LiveQueryClient` but isn't this a performance advantage, as there are less connections to the server?

**Comment by RodrigoSMarques** [comment]
@fischerscode 

I checked LiveQuery on Android and it's not Singleton. I have a native app (java) with more than two LiveQuery.

Let's take for example Whatsapp, where you have a list of conversations that needs to be updated when a message arrives and a list of messages that needs to be updated in the chat.

My current case on Flutter, I have a screen with two sessions. Each session needs to be updated live by different LiveQuery, due to the QueryBuilder criteria.

I've been testing it for a few days and I haven't identified any performance issues. When I leave the screen, I disconnect LiveQuery and release that session on the server.

I had a problem with the current implementation. As a SingleTon, the session is active for the entire life of the app.

When disconnecting without passing the userInitialized parameter, LiveQuery was doing reconnect and creating multiple connections, which reached the point of bursting my server's memory.

And this was multiple times. It took me a long time to realize that a session of the app that was being tested on my simulator was that it was recreating multiple sessions on the server.

**Comment by fischerscode** [comment]
@RodrigoSMarques 
Maybe I misunderstand your problem.

> When I create a LiveQuery, I cannot have another one with different criteria.

I am using ParseLiveList (which uses LiveQuery) all over my app and having two visible lists with different queries works as expected. So I am pretty sure this works:
> Let's take for example Whatsapp, where you have a list of conversations that needs to be updated when a message arrives and a list of messages that needs to be updated in the chat.

**Comment by fischerscode** [comment]
@RodrigoSMarques 
I've created an [example](https://github.com/fischerscode/Parse-SDK-Flutter/tree/example_multiple_livequeries/packages/dart/example_multiple_livequeries) how I use multiple `LiveQueries`.

**Comment by RodrigoSMarques** [comment]
@fischerscode 

I have to confess that I rushed into this PR.

After your comment I redid the tests on another project that I just created. I analyzed the code calmly and managed to use LiveQuery with two different Query.

LiveQuery is just a client and in that sense it makes sense to be a Singleton, just like ParseHTTPClient.

Now I'm going to check what's wrong with my project. Because it didn't work there.

I will cancel the PR and keep only the other changes.

**Comment by fischerscode** [comment]
@RodrigoSMarques 
I wish you good luck finding the issue.
For me, non working LiveQueries have often been caused by forgetting to tell the server that the new table should be "livequeryable".

**Pull request closed without merging**
