### PR TITLE
refactor: Resolve analyzer info errors in Flutter SDK example

### PR DESCRIPTION
**Pull request by Nidal-Bakir**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

## Issue

Closes: #910

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Review by mbfakourii — DISMISSED** [review]
Great

**Comment by mtrezza** [comment]
CI failed, should this PR be merged anyway because it fixes only a part?

**Comment by mbfakourii** [comment]
> CI failed, should this PR be merged anyway because it fixes only a part?



> CI failed, should this PR be merged anyway because it fixes only a part?

This error is related to Dart version, I think you should merge #908 first, then merge this PR

**Comment by mtrezza** [comment]
CI is still failing.

**Comment by mbfakourii** [comment]
We have another warning in Flutter 3.10
```info • Use 'const' with the constructor to improve performance • packages/flutter/example/lib/live_list/main.dart:52:23 • prefer_const_constructors```

@Nidal-Bakir 
I think it needs ```const```

**Comment by Nidal-Bakir** [comment]
Thats a problem!
We can not use `const` here because its only support in flutter 3.10.0

**Comment by mbfakourii** [comment]
> Thats a problem! We can not use `const` here because its only support in flutter 3.10.0

I think it is better to create a variable and then give the variable to child

**Comment by Nidal-Bakir** [comment]
That's a good idea.
but it is a temporary solution.

I'm starting to smell a revert PR. for this PR #906 and a remove for the `--fatal-infos` flag

Any new rules/lints in Flutter 3.10.0 that can not be applied in Flutter <3.10.0 will cause a problem.

**Comment by Nidal-Bakir** [comment]
@mbfakourii  
I think we need to remove the `--fatal-infos` flag from CI/CD. because we are testing on Flutter version 3.3 up to 3.10. More issues like this will rise.

**Comment by mbfakourii** [comment]
> @mbfakourii  
> I think we need to remove the `--fatal-infos` flag from CI/CD. because we are testing on Flutter version 3.3 up to 3.10. More issues like this will rise.
> 

Are the warnings completely hidden by removing this item, for example the format code?

**Comment by mbfakourii** [comment]
> @mbfakourii  
> I think we need to remove the `--fatal-infos` flag from CI/CD. because we are testing on Flutter version 3.3 up to 3.10. More issues like this will rise.
> 

Are the warnings completely hidden by removing this item, for example the format code?

**Comment by Nidal-Bakir** [comment]
This has nothing to do with the code format. That's a other command called `dart format`

**Comment by mbfakourii** [comment]
> This has nothing to do with the code format. That's a other command called `dart format`

I'm afraid we're missing some warnings, if you're sure, then remove them

**Comment by Nidal-Bakir** [comment]
We will likely miss some warning or info messages if we remove the `--fatal-infos` flag. Alternatively, we could monitor if this causes any issues and remove it if necessary.

**Comment by Nidal-Bakir** [comment]
We are good to go!

**Review by mtrezza — APPROVED** [review]
Looks good!

**Pull request merged**
