### PR TITLE
feat: Upgrade various dependencies and fix warnings in Flutter package

### PR DESCRIPTION
**Pull request by mbfakourii**
### New Pull Request Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description
All versions and packages in the Flutter package have been updated to the latest version and the warnings have been fixed

Closes: #821

### Approach
n/a

### TODOs before merging
- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] A changelog entry

### CODE REVIEW

**Comment by mbfakourii** [comment]
@mtrezza 
What is the need for ```codecov/patch Failing after 1s — 0.00% of diff hit (target 16.36%)``` checks if it always says wrong, in my opinion, the test should be chosen by the managers for the PR owner.

**Comment by mtrezza** [comment]
It's probably a minimum coverage that is expects?

**Comment by mbfakourii** [comment]
> It's probably a minimum coverage that is expects?

No, by the way, many lines say to write a test, which is not necessary

**Comment by mtrezza** [comment]
Let's look at the coverage in a separate issue then.

**Comment by mtrezza** [comment]
This is a breaking change, as it upgrades to nio 5 and parse dart 4. So I'd merge this together with the breaking change of package renaming.

**Review by Nidal-Bakir — DISMISSED** [review]
LGTM

**Comment by Nidal-Bakir** [comment]
@mtrezza 
this

**Review by mtrezza — CHANGES_REQUESTED** [review]
please add a changelog entry

**Comment by mtrezza** [comment]
Once this is merged, we can publish the flutter 4.0 release.

**Comment by mbfakourii** [comment]
flutter version bumped and entry added in CHANGELOG.md

**Review by Nidal-Bakir — APPROVED** [review]

**Review by mtrezza — CHANGES_REQUESTED** [review]
To give more details about the changelog convention we're using across Parse Platform:
- a `feat` PR must have an entry in the `### Features` section which is (except in specific cases) the same as the PR title
- the `### BREAKING CHANGES` section is an additional section in which a PR that includes a breaking change must make a note *in addition* to the entry in the `### Features` section.
- the entries mentioned above always reference the GitHub pull request, not the GitHub issue; that's because a commit may not have an issue associated with it, but it (usually) always has a pull request; in the past we were sometimes referencing issues which we don't do anymore.

I'll commit the changes.

**Review by Nidal-Bakir — APPROVED** [review]

**Comment by mtrezza** [comment]
Great, let's wait for @mbfakourii's confirmation as well, then I'll go ahead and merge.

**Comment by mbfakourii** [comment]
> Great, let's wait for @mbfakourii's confirmation as well, then I'll go ahead and merge.

For now, let's move to a higher version. We need more time to discuss the merge of the two libraries.

**Review by mtrezza — APPROVED** [review]
Looks good

**Pull request merged**
