### PR TITLE
Small changes and improvements

### PR DESCRIPTION
**Pull request by fischerscode**
Some small changes and improvements like changing the Parse Logo, adding "tests" and adding a default CoreStore for dart.

### CODE REVIEW

**Comment by fischerscode** [comment]
Any idea why this fails? I have done nothing with travis before.

**Comment by phillwiggins** [comment]
Don't worry, it runs the unit tests (Which there an extremely minimal amount, and are broken).

This package could really use some tests. I started it as an introduction to Dart but didn't TDD.

**Comment by fischerscode** [comment]
Ok, should I remove 159d59aaac4530890fbe48e47c69bf72918c53fe again?

**Comment by phillwiggins** [comment]
No it's fine. We should probably just update the tests that are there now to make Travis CI pass. There's only 2 I believe?

**Comment by fischerscode** [comment]
There are currently almost no tests. They are more like, if I initialize the parse, is the application name set correctly.

**Pull request merged**
