### PR TITLE
Fix queryParam to JSON

### PR DESCRIPTION
**Pull request by jjunineuro**
Fix the conversion to JSON of Map with the POST request parameters. Thanks @nstrelow

From: [https://github.com/parse-community/Parse-SDK-Flutter/pull/544#issuecomment-758679406](https://github.com/parse-community/Parse-SDK-Flutter/pull/544#issuecomment-758679406)

### CODE REVIEW

**Comment by nstrelow** [comment]
Awesome, this should go to the development branch probably ;)

**Comment by nstrelow** [comment]
I think you need to change the branch of this PR to development

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by jjunineuro** [comment]
> I think you need to change the branch of this PR to development
> 
> https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

But I have to change my Fork, right? And how do I request a PR?

**Comment by nstrelow** [comment]
Just close this one and open a new one :)

**Comment by RodrigoSMarques** [comment]
Wrong branch. Pull request made using #547

**Pull request closed without merging**
