### PR TITLE
refactor: Fix unsupported platform `web` in pub.dev

### PR DESCRIPTION
**Pull request by mbfakourii**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

## Issue
fix unsupported platform `web` in pub.dev

Closes: #781

## Approach
n/a

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by mbfakourii** [comment]
@parse-community/flutter-sdk-review 

It is possible to check, it seems ready to merge

**Review by mtrezza — APPROVED** [review]
Looks good, waiting for another approval...

**Comment by mbfakourii** [comment]
@Nidal-Bakir Do you think it's ready to merge?

**Comment by Nidal-Bakir** [comment]
Surely it is.

**Pull request merged**
