### PR TITLE
Change to the method to POST in the Login

### PR DESCRIPTION
**Pull request by jjunineuro**
Change to the method to POST in the Login object to make the request to the Parse Server.

**Resolved issue**: [https://github.com/parse-community/Parse-SDK-Flutter/pull/544#issuecomment-758679406](https://github.com/parse-community/Parse-SDK-Flutter/pull/544#issuecomment-758679406)

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
Thank you for your contribution

**Comment by jjunineuro** [comment]
Hi @RodrigoSMarques,

When will the new 2.0.2 release be published?

Thanks

**Comment by RodrigoSMarques** [comment]
Hi @jjunineuro 
I wish I had an answer, but I don't know.

The package is not in my name, so I can't generate a new release. I have to talk to the owner of the package.

The new version for me should be "2.1.0".

Changes were made to the package structure, for example, defining that you want to use the DIO or HTTP package.

I identified two problems in this release:
1 - Save and recover ParseInstallation is not working properly
2 - File upload is not working with the DIO package.

I tried to identify the problem and I couldn't.

In ParseInstallation I will try to identify who made the last change, because it was working before.

In Upload, I notified the dev who made the changes to have the DIO / HTTP options, but he did not respond.

**Comment by jjunineuro** [comment]
Thank you very much for the installations, but I can help in correcting these errors, can you tell me the files in which you are causing the 2 error points?
I am interested in always supporting the community and using the login change for security to use the package.

**Comment by phillwiggins** [comment]
@RodrigoSMarques 

Let me know when you feel confident that we have a safe release ready. I'll release on your command 👍

**Comment by RodrigoSMarques** [comment]
@jjunineuro 
There are some open issues.
#551, #529 #505 

There was a PR for correction, but it seems that it didn't work.

Are you Carlos Albuquerque who sent me an email? I can pass details by email in Portuguese, to facilitate.

**Comment by RodrigoSMarques** [comment]
Hello @phillwiggins , thank you. I'll let you know when it's ready.

I was going to make contact to release the new version, but when running my package validation project, I found these two issues and consider them critical.

I sent a message to @fischerscode  that created the dio option in the package, but he hasn't returned it yet.

**Comment by jjunineuro** [comment]
> @jjunineuro
> There are some open issues.
> #551, #529 #505
> 
> There was a PR #497 for correction, but it seems that it didn't work.
> 
> Are you Carlos Albuquerque who sent me an email? I can pass details by email in Portuguese, to facilitate.

Yes, you can send the details to this email.
Thank you!

**Comment by RodrigoSMarques** [comment]
Hi @phillwiggins 
I sent you an email. You received?

**Pull request merged**
