### PR TITLE
Added ParseClient to abstract dio and http

### PR DESCRIPTION
**Pull request by fischerscode**
It seems like there is a [performance issue](https://github.com/parse-community/Parse-SDK-Flutter/issues/489#issuecomment-711153742) with dio on web.
This changes allow the developer to use either http or dio as the default client.
(Dio is needed in order to support progressCallbacks)

### CODE REVIEW

**Comment by gorillatapstudio** [comment]
Are we about to release this? Looking forward to this

**Comment by fischerscode** [comment]
I've tested this for a while now and everything seems to work.
I think after a few more finishing touches (Docs) this can me merged and released.

@gorillatapstudio 
Did you run this change? And if yes, did you encounter any problems?

**Comment by fischerscode** [comment]
@phillwiggins 
What do you think about this change?
It allows the developer to chose the network library. Implementing a custom client would also be possible.
(The "tests" fail as the flutter package uses the development branch in the dependencies. When running local, the test finishes.)

**Comment by gorillatapstudio** [comment]
@fischerscode yes, i'm using this branch for the past two to three weeks and no issue happened to me yet.

**Comment by phillwiggins** [comment]
@fischerscode 

I really like that idea. Great way to keep everyone happy. I prefer modular approaches as they allow everyone to use thier preferred tooling.

**Comment by fischerscode** [comment]
I've now merged this.
I think, as this is no breaking change, this could be released in 2.1.0

**Comment by nstrelow** [comment]
On the newest development branch I cannot create an anonymous login.

**Comment by fischerscode** [comment]
I will have a look at this.

**Comment by fischerscode** [comment]
@nstrelow 
Thanks for 'issue'! This would have been a pretty nasty bug.
https://github.com/parse-community/Parse-SDK-Flutter/commit/7668ae8132f109c3bc788f4c06214560c90901a6 should fix this.

**Comment by nstrelow** [comment]
Whuuu thanks a lot :D

Sorry I didn't have the time to help more

**Comment by fischerscode** [comment]
@nstrelow 
Your report was help enough. The issue was pretty easy to spot.

**Comment by RodrigoSMarques** [comment]
@fischerscode 
Uploading file is not working with Dio in Flutter project.

To work I had to change the clientCreator to ParseHTTPClient.

Can you check the problem? We need to release this version, there are many bugfix in it.

**Pull request merged**
