### PR TITLE
Parsequery OR

### PR DESCRIPTION
**Pull request by maaeps**
Added a second constructor to ParseQuery for creating OR Queries.
#213 

Tested with basic queries.
Works with live query, too.

### CODE REVIEW

**Comment by phillwiggins** [comment]
That looks really promising! Good effort. I tried looking at this a while ago but ended up giving up. That looks like a promising solution.

**Comment by RodrigoSMarques** [comment]
@maaeps 
Very good. I also started to develop this in the past, but due to lack of time I was unable to progress.

**Comment by RodrigoSMarques** [comment]
It is on my list to complete the rest of the functions with GeoPoint. Some are still missing. I got involved with other plugins, but I intend to go back and finish.

**Comment by maaeps** [comment]
Thanks for merging.
The parsing of the subqueries is a little goofy.
Maybe someone will find a more pretty solution.

**Pull request merged**
