### PR TITLE
ci: Add `pub publish --dry-run` for Flutter package

### PR DESCRIPTION
**Pull request by Nidal-Bakir**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description

Closes: #847

### Approach
start a job to check for any errors when running `dart pub publish --dry-run` For the Flutter package

### TODOs before merging

Merge this PR first #846 

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] A changelog entry

### CODE REVIEW

**Comment by mtrezza** [comment]
@Nidal-Bakir just to explain the bot, most labels incl. `type:` can only be used on issues.

**Comment by Nidal-Bakir** [comment]
@mtrezza

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by mtrezza** [comment]
@Nidal, it seems this CI addition also fails in https://github.com/parse-community/Parse-SDK-Flutter/pull/846, so another fix may be needed, could you look into this?

**Pull request merged**
