### PR TITLE
ci: Add publish dry-run check for dart package

### PR DESCRIPTION
**Pull request by Nidal-Bakir**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description

Closes: #839

### Approach

start a job to check for any errors when running `dart pub publish --dry-run` 

### TODOs before merging
All set

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] A changelog entry

### CODE REVIEW

**Comment by Nidal-Bakir** [comment]
@mtrezza 
Do you know why I can not redirect the stdout/stderr to a file in GitHub action?

`(dart pub publish --dry-run 1> flutter_dry_run_stdout 2> flutter_dry_run_stderr)`

**Comment by mtrezza** [comment]
What is this error? Should we rename a package?

**Comment by Nidal-Bakir** [comment]
@mtrezza 
We just need to rename the file in `Parse-SDK-Flutter/packages/flutter/lib` 
from `parse_server_sdk.dart`  to `parse_server_sdk_flutter.dart`

Note that anyone is importing the file using the old name will get an error but its fine nothing to worry about

**Comment by mtrezza** [comment]
So this change won't break the app at runtime because the developer will always use an IDE and the compiler will always throw an error?

**Comment by Nidal-Bakir** [comment]
> this won't be a breaking change for existing apps
No. any user of the package will get compile time error.

But it is annoying because let's say you have 15 files and in each one of them you are importing the old file name. in this case you need to fix each one of them using the new file name import.

**Comment by mtrezza** [comment]
I think then formally it is a breaking change, as it requires a migration, no matter how easy the migration is. Nothing wrong with that - we have a "Breaking Change" section in our changelog style where we can add details about how to migrate. The major version increment will also highlight to users that a manual migration needs to be done.

**Comment by Nidal-Bakir** [comment]
Got it, in this case, if we will introduce a breaking change let's make it count. I mean introducing a breaking change just because we changed the way the package is been imported is not enough of a reason I think.

>How about we merge the renaming PR first, then this PR with dart + flutter dry-run?

I do not think it's a good idea because the package users already using the import as it is. and it is not a big deal. I suggest merging this PR with a dry-run for dart only for now. 

And after that, we will open a new 2 PRs:
* renaming the file
* adding a dry-run for flutter 

and not merge them right away we wait and see if any bug or feature or other reason requires a breaking change then we merge these 2 PRs with the newly introduced breaking change if any, if no breaking change is introduced for example 1 or 2 months then we can merge this 2 PRs.

> Since we'll do a major version release, we can also add other breaking changes (in separate PRs) if you can think of any. Just for efficiency as we try to accumulate breaking changes into a single major release. That is to not surprise developers with breaking releases too often.

You are right. so as I stated earlier let us wait about 1 to 2 months and decide then what to do. 

What do you think?

**Comment by mtrezza** [comment]
That sounds good. Let me try to make the pending flutter release that failed last time. It should be fixed with https://github.com/parse-community/Parse-SDK-Flutter/issues/837 right?

**Comment by Nidal-Bakir** [comment]
Yes, we fix it.

**Comment by mtrezza** [comment]
I tried to release flutter, but it failed - obviously - because it's also doing the dry-run before the actual publishing to ensure all goes well. It now only fails for the reason of the naming issue.

**Comment by Nidal-Bakir** [comment]
how this error did not prevent older releases?
I thought it is just a warning

**Comment by mtrezza** [comment]
Hah, good question!

**Comment by Nidal-Bakir** [comment]
I do not recommend option (b). Forcibly pushing the package to pub.dev is not a good idea `dry-run` is there for a good reason.

on the other hand, If we choose option (a), we won't be able to release bug fixes until we decided it's time to fix this and introduce a breaking change.

I think option (a) is the more suitable and let's wait for a week or two and introduce a breaking change with any bug fixes if any.

**Comment by mtrezza** [comment]
> we won't be able to release bug fixes until we decided it's time to fix this and introduce a breaking change.

How so? We can release bug fixes any time after the release of Flutter 4.0.0

**Comment by Nidal-Bakir** [comment]
> My thinking is, it would be nice to wait with (a) until we have more stuff for a breaking change release

I thought that we will wait a bit before we release flutter 4.0.0

**Comment by Nidal-Bakir** [comment]
We can do it now if you do not have any issues with it

**Comment by mtrezza** [comment]
Sure we can wait, why would you wait?

**Comment by mtrezza** [comment]
I follow you on this, what do you suggest, wait or release?

**Comment by Nidal-Bakir** [comment]
In situations like this, it would be wise to wait a few days. We do not want to rush anything.

Tomorrow or the day after tomorrow, I will open a new issue and PR to introduce the breaking change for the flutter package.

**Comment by mbfakourii** [comment]
> That sounds good. @mbfakourii what do you think?
> 
> Let me try to make the pending flutter release that failed last time. It should be fixed with #837 right?

Yes, I think it's good too

**Comment by mtrezza** [comment]
Should we merge this PR already as dart-only or after the flutter major release with dart + flutter?

**Comment by Nidal-Bakir** [comment]
Yes, let's merage this as add dry-run for the dart package. 

I will open a new 2 PRs:

 *   renaming the file so we fix the wrong import for the flutter package
 *   adding a dry-run for flutter

**Review by mtrezza — APPROVED** [review]
Looks good!

**Pull request merged**
