### PR TITLE
test: Fix failing tests in Flutter example project

### PR DESCRIPTION
**Pull request by zhangwb1996**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description

fixed the errors of test

image

### TODOs before merging

-  Add tests
-  Add changes to documentation (guides, repository pages, in-code descriptions)
-  A changelog entry

### CODE REVIEW

**Review by mbfakourii — APPROVED** [review]
The code was tested. All tests passed. 
Thanks for solving the problem.
You may choose a good title for this PR?

**Comment by zhangwb1996** [comment]
> The code was tested. All tests passed. 
> Thanks for solving the problem.
> You may choose a good title for this PR?
is there any suggestions?

**Comment by mtrezza** [comment]
If this only fixes failing tests, but there is no actual change in the product code, then we use `test` as commit type so it won't be in the changelog (because it has no relevance for the product); something like:

`test: Fix failing tests in Flutter example project`

**Review by mtrezza — APPROVED** [review]
Looks good, is this ready for merge?

We won't publish a release for commit type `test`, so there is no need for a changelog entry.

**Comment by mbfakourii** [comment]
> 

Yes, I think the merge is ready

**Review by mbfakourii — APPROVED** [review]
Yes, I think the merge is ready

**Pull request merged**
