### PR TITLE
fix: Update dio

### PR DESCRIPTION
**Pull request by mbfakourii**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

## Issue

Closes: #958

## Approach
Update dio to ```dio: ^5.3.2```

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good, could you write a PR title that describes the issue (not the solution)

**Comment by mbfakourii** [comment]
> Looks good, could you write a PR title that describes the issue (not the solution)

I have no other idea, only dio was updated, the reason was a bug in the dio package

**Comment by mtrezza** [comment]
Why did we have to update the dio package, if we are using a range operator anyway?

```diff
- dio: ^5.2.0+1
+ dio: ^5.3.2
```

If I understand this correctly, as soon as a new version (non-major) version is released, it will be updated anyway?

**Comment by mbfakourii** [comment]
> Why do we have to update the dio package, if we are using a range operator anyway?
> 
> ```diff
> - dio: ^5.2.0+1
> + dio: ^5.3.2
> ```
> 
> If I understand this correctly, `^5.2.0+1` will use the latest dio version <6.0.0 as soon as a newer version is released, right?

Because of [these issues](https://github.com/parse-community/Parse-SDK-Flutter/issues/958), we have to give a new version quickly because the current version [cannot be used](https://github.com/parse-community/Parse-SDK-Flutter/issues/958#issuecomment-1661922253).

I checked the dio package and did not see anything from version 6

**Comment by mtrezza** [comment]
But why do we have to update our package? In my understanding, the Parse Flutter SDK will always install the latest release of dio <6, because the dependency is `^5.2.0+1`. So even if we don't update the package, Parse Flutter SDK should use `5.3.2`, not `5.2.0`.

**Comment by mbfakourii** [comment]
Yes, I think the problem was solved with [Revert](https://github.com/cfug/dio/pull/1916) on the dio side!
I am waiting for the answer of [those who have problems](https://github.com/parse-community/Parse-SDK-Flutter/issues/958#issuecomment-1666484787)

**Comment by mtrezza** [comment]
I think we should see this also in our [CI](https://github.com/parse-community/Parse-SDK-Flutter/pull/956#issuecomment-1666501726).

**Comment by mbfakourii** [comment]
> I think we should see this also in our [CI](https://github.com/parse-community/Parse-SDK-Flutter/pull/956#issuecomment-1666501726). In fact the CI previously failed and now passes. In my opinion this PR can be closed, as well as the related issue, because it was a dio issue, not a Parse issue.

sure

**Pull request closed without merging**
