### PR TITLE
refactor: Add Flutter code documentation and resolve `StreamController` warning

### PR DESCRIPTION
**Pull request by mbfakourii**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

## Issue

Closes: #903

## Approach
add document
and fix bug `StreamController`

## Tasks

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by mtrezza** [comment]
Is this a bug fix? If so, we'll merge this as `fix` instead of `refactor` and just accept the (unrelated?) docs changes in this PR without mentioning them in the changelog.

**Comment by mbfakourii** [comment]
> Is this a bug fix? If so, we'll merge this as `fix` instead of `refactor` and just accept the (unrelated?) docs changes in this PR without mentioning them in the changelog.

No, it is a refactor and not a fix. For pub.dev only

**Comment by mtrezza** [comment]
What does "fix bug StreamController" in the PR title refer to?

**Comment by mbfakourii** [comment]
> What does "fix bug StreamController" in the PR title refer to?

I changed the title. `StreamController` is just a warning

**Pull request merged**
