### PR TITLE
fix: Updating and deleting a ParseObject sends requests even if object ID is null

### PR DESCRIPTION
**Pull request by Nidal-Bakir**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description

Closes: [#828](https://github.com/parse-community/Parse-SDK-Flutter/issues/828)

### Approach
Use `assert()` to make sure that the `objectId` is valid and can be used

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry

### CODE REVIEW

**Comment by Nidal-Bakir** [comment]
I will write the tests for these changes in my other [PR](https://github.com/parse-community/Parse-SDK-Flutter/pull/827). because I don't want to create a conflict.

**Review by mbfakourii — DISMISSED** [review]
The code was tested and looks good

**Comment by mtrezza** [comment]
Since this is a fix, could you add a change log entry using the title of this PR? So we can merge this.

**Comment by Nidal-Bakir** [comment]
@mtrezza 

> It would also be great if you could add a test for the bug that is fixed here, so we can prevent this from happening in the future.

Adding tests now will create a merge conflict on my other [PR](https://github.com/parse-community/Parse-SDK-Flutter/pull/827).

**I will add tests for this on my other PR.**

**Comment by mtrezza** [comment]
Got it, thanks for adding the changelog entry, let's wait for the CI and then merge this...

**Review by mtrezza — APPROVED** [review]

**Pull request merged**
