### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 7flash**

### CODE REVIEW

**Review by TomWFox — APPROVED** [review]
Thanks for the PR!

**Comment by TomWFox** [comment]
@fischerscode @RodrigoSMarques is it cool to merge this change straight into the master branch?

**Comment by RodrigoSMarques** [comment]
> is it cool to merge this change straight into the master branch?

Hi @TomWFox.

No. The current branch is nullsafety.

The master is updated when we release a new version.

I am working on a big project that will be implemented tomorrow and in the last few weeks, I am not having time to check the issues and PR of the repository.

Next week I will be able to go back to work pending the repository.

**Comment by RodrigoSMarques** [comment]
Thanks for your PR.

**Comment by mtrezza** [comment]
@RodrigoSMarques We are working on an automated release system for the Parse repos. Would you be available for a quick chat on Slack anytime soon to talk about the current branch strategy in this repo?

**Comment by RodrigoSMarques** [comment]
Hi @mtrezza 

Sorry for the delay.

I'll get in touch with Slack.

It would be interesting @phillwiggins to participate.

I've been organizing the bugs and PR, but he's the one that makes the release available.

**Comment by mtrezza** [comment]
Great, yes, @phillwiggins please join if you can, I suggest we coordinate on Slack to find a time that works for everyone.

**Comment by RodrigoSMarques** [comment]
Hi @mtrezza .

I used slack a few times, I don't know how to use it.

I couldn't locate you.

If you can get in touch with me: rodrigosmarques

**Comment by mtrezza** [comment]
I have sent you an invite via email.

**Comment by 7flash** [comment]
Thanks

**Pull request merged**
