### PR TITLE
Release/2.0.0

### PR DESCRIPTION
**Pull request by fischerscode**
As pointed out by @RodrigoSMarques in #478, the name of version 1.0.28 is not optimal and should be named 2.0.0.
- Added warning to parse_server_sdk changelog
- Added warning to parse_server_sdk readme

When releasing, the dart package has to be released first, as the flutter package depends on it.

The tests should fail, as `parse_server_sdk: ^2.0.0` is not available.

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
Good job!!

**Comment by fischerscode** [comment]
I am going to add the changes that will make pub.dev recognize, that this works on web.
Then we can merge and release this.

**Comment by fischerscode** [comment]
> I am going to add the changes that will make pub.dev recognize, that this works on web.

Never mind, as `parse_server_sdk.dart` currently contains `import 'dart:io';`, doing this change might take a little longer.
But even trough this line exists and pub.dev wont recognize this package as web compatible, it should work. (I am testing my app on web since weeks already.)

**Comment by fischerscode** [comment]
@phillwiggins 
I think this is ready. Adding "pub.dev-level" web support is something for a future release.

**Pull request merged**
