### PR TITLE
Added headers to ParseUser.destroy which are also passed to ParseHTTPClient.delete

### PR DESCRIPTION
**Pull request by matskosan**
I needed to send headers to cloud triggers beforeDelete and afterDelete.

### CODE REVIEW

**Comment by matskosan** [comment]
I just send a custom text header 'x-password-confirmation' with the user password that I check in 'beforeDelete' trigger on Parse.User to make sure this is the actual owner who wants do delete the account and not someone else. This surely can be used to send any other headers.

**Comment by davimacedo** [comment]
I think that's not the best way to be done. In order to create this feature, I'd recommend creating a cloud code function that receives the password, do the verification, and, in case of success, delete the user. Then you can disable the delete access from the _User class CLP so you can make sure that users will only be deleted through this cloud code function.

I am not sure if it is a good idea to allow the developers to pass arbitrary headers through the SDK.

**Comment by matskosan** [comment]
The 'delete' cloud function was my initial approach. However, I also felt that having this check in a trigger feels more 'natural', as the functionality is already there. Maybe it makes sense to change parse server in a way that deleting some objects would require owner's password?

I am fine cancelling the pull request though and creating the cloud function. Is it how everyone else does this?

**Comment by matskosan** [comment]
Do you know if there is a way to set up CLP using code so that is stays consistent between deployments?

**Comment by davimacedo** [comment]
@matskosan I think that the best way is really the usage of cloud code. In terms of CLP, you can take a look in this issue: https://github.com/parse-community/parse-server/issues/5888

**Pull request closed without merging**
