### PR TITLE
docs: update changelogs

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description
- Changelogs are restyled according to Parse Org-wide style
- Changelog entry for release 3.1.1 is added

Related issue: #668 

### Approach
n/a

### TODOs before merging
n/a

### CODE REVIEW

**Comment by mtrezza** [comment]
@fischerscode I don't understand the changelogs; the logs for dart and flutter are identical from 2.0.0 onwards, but these are 2 different packages. How come?

**Comment by fischerscode** [comment]
@mtrezza Originally, there was only one package. Then it got split in the dart and the flutter package. In order to make the changes of the dart package [transparent](https://pub.dev/packages/parse_server_sdk_flutter/changelog) to the users of the flutter one, changes where added to both. The two packages where treated as one.
But it might be better to stop doing it like this.

**Comment by mtrezza** [comment]
Yes, it seems weird. I can also imaging that there may be a change in the Flutter package that has nothing to do with the darf package, but it would appear in the dart changelog. I am beginning to doubt whether we should really keep the versions in sync.

**Comment by mtrezza** [comment]
I've added version 3.1.1 only to the flutter changelog, since it's the flutter example app, unrelated to dart.

**Review by fischerscode — COMMENTED** [review]
LGTM

**Review by fischerscode — APPROVED** [review]
LGTM (clicked the wrong button)

**Pull request merged**
