### PR TITLE
ci: bump versions for next release

### PR DESCRIPTION
**Pull request by fischerscode**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description
Bumping the versions, since #734 did not cover it.

Related issue: #733 

### Approach
~Left the `parse_server_sdk` dependency in the flutter package at `^3.1.0`.~

Not sure if the title really fits. Feel free to edit. `ci:` seems best to me.

### TODOs before merging
n/a

### CODE REVIEW

**Review by mtrezza — CHANGES_REQUESTED** [review]
I think you'd also need to change the dart dependency version in the flutter package

**Comment by fischerscode** [comment]
> but we want to test the release process

👍

**Review by mtrezza — APPROVED** [review]
Looks good, lets make the release

**Comment by mtrezza** [comment]
Worked nicely, thanks for this PR for testing, so we can be sure now.

**Pull request merged**
