### PR TITLE
Nullsafety fixes

### PR DESCRIPTION
**Pull request by nstrelow**
More fixes for @RodrigoSMarques 😁 

Hopefully this is it, but I don't count on it.

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
I have already made the changes and have been tested. I will go up to my repo and send a PR.

My test project performed all the steps without error.

I believe that we can release a first version with nullsafety.

**Comment by nstrelow** [comment]
Nice, did you make the same changes as I did? @RodrigoSMarques

**Comment by RodrigoSMarques** [comment]
> Nice, did you make the same changes as I did? @RodrigoSMarques

Yes and they have already been tested. 

I reported, to try to find out why in your project they didn't happen. You explain that you use Shared Preference

**Comment by RodrigoSMarques** [comment]
Fix performed in another PR

**Comment by nstrelow** [comment]
@RodrigoSMarques Well you did not include everything.

Could have at least cross checked, as I try make my commits informative.

**Pull request closed without merging**
