### PR TITLE
ParseLiveList

### PR DESCRIPTION
**Pull request by maaeps**
As many Apps are build around dynamic lists, where items are added, loaded, removed and reordered,
I decided to implement a 'LiveList' to simplify the implementation.

Have a look in the README for further information.

Please consider merging this new feature.
Cheers!

### CODE REVIEW

**Comment by RodrigoSMarques** [comment]
@maaeps 
Tip: If possible, update the sample application using this Widget.

**Comment by maaeps** [comment]
@RodrigoSMarques 
Good idea!
I will do so.

**Comment by phillwiggins** [comment]
Wow, that's a really nice feature? More than happy to merge in. Shall I wait for the sample app to be updated?

Does any other Parse SDK have this feature? I really like it.

**Comment by maaeps** [comment]
@phillwiggins 
I will try to update the sample app right now.
So we can wait, I guess.

I only worked with the Android SDK jet. There was nothing like this.

**Comment by maaeps** [comment]
Somehow I can't get the example working.
(can't login nor sign up)

@phillwiggins @RodrigoSMarques 
Does anyone mind, me creating a second example for this feature?

**Comment by phillwiggins** [comment]
That's absolutely fine. Just create a second sample app and call it what
you want. Just do it in a similar style to the other app, i.e. same package
level.

Cheers

**Comment by maaeps** [comment]
I added a very simple example.
Feel free to make it more advanced ;-)

**Comment by phillwiggins** [comment]
Excellent work. I'm going to run a few tests on the latest version (1.0.26) and release today if everything seems okay. Any objections @maaeps  @RodrigoSMarques ?

**Comment by maaeps** [comment]
@phillwiggins
I have one more performance improvement.
It's marked as TODO in the livelist file.
I will commit this improvement today.

I also thought about providing the itemBuilder some kind of snapshot (similar to FutureBuilder)
That might make improvements in the future simpler.
What do you think about that?

Apart form that, I think a release should be fine.

**Comment by phillwiggins** [comment]
I think add the performance improvement today, leave the other idea until after today.

I will run a few tests my end and if all is well we will release today. I think there's a bug with 1.0.25.

**Comment by RodrigoSMarques** [comment]
Hi @maaeps 
ParseLiveList not working in Flutter Web.
I did a Parse lib test on Flutter Web and had several errors even without using ParseLiveList.

Version 1.0.25 its OK.

Many compile erros:
```dart

Compiler message:
../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart:68:3: Error: Type 'Subscription' not found.
  Subscription _liveQuerySubscription;
  ^^^^^^^^^^^^
../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart:69:22: Error: Type 'LiveQueryClientEvent' not found.
  StreamSubscription<LiveQueryClientEvent> _liveQueryClientEventSubscription;
                     ^^^^^^^^^^^^^^^^^^^^
../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart:68:3: Error: 'Subscription' isn't a type.
  Subscription _liveQuerySubscription;
  ^^^^^^^^^^^^
../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart:69:22: Error: 'LiveQueryClientEvent' isn't a type.
  StreamSubscription<LiveQueryClientEvent> _liveQueryClientEventSubscription;
                     ^^^^^^^^^^^^^^^^^^^^
../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart:101:16: Error: 'Subscription' isn't a type.
        .then((Subscription<T> subscription) {
               ^^^^^^^^^^^^
../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart:113:18: Error: 'LiveQueryClientEvent' isn't a type.
        .listen((LiveQueryClientEvent event) async {
                 ^^^^^^^^^^^^^^^^^^^^
../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart:98:10: Error: The getter 'client' isn't defined for the class 'LiveQuery'.
 - 'LiveQuery' is from 'package:parse_server_sdk/src/network/parse_live_query_web.dart' ('../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/network/parse_live_query_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'client'.
        .client
         ^^^^^^
../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart:111:10: Error: The getter 'client' isn't defined for the class 'LiveQuery'.
 - 'LiveQuery' is from 'package:parse_server_sdk/src/network/parse_live_query_web.dart' ('../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/network/parse_live_query_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'client'.
        .client
         ^^^^^^
../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart:114:20: Error: The getter 'LiveQueryClientEvent' isn't defined for the class 'ParseLiveList<T>'.
 - 'ParseLiveList' is from 'package:parse_server_sdk/src/utils/parse_live_list.dart' ('../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'LiveQueryClientEvent'.
      if (event == LiveQueryClientEvent.CONNECTED) {
                   ^^^^^^^^^^^^^^^^^^^^
../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/utils/parse_live_list.dart:239:19: Error: The getter 'client' isn't defined for the class 'LiveQuery'.
 - 'LiveQuery' is from 'package:parse_server_sdk/src/network/parse_live_query_web.dart' ('../../../../Rodrigo/flutter/.pub-cache/git/Parse-SDK-Flutter-f8af2b658e93c4e3ac9b9d89ed6b0a6603edcd5e/lib/src/network/parse_live_query_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'client'.
      LiveQuery().client.unSubscribe(_liveQuerySubscription);
                  ^^^^^^

``

**Comment by maaeps** [comment]
@RodrigoSMarques 
I think LiveQuery uses a different sourcecode on web.
I will have a look at it.
Can you please create a seperate issue for this?

**Comment by maaeps** [comment]
@RodrigoSMarques 
This should be fixed with #340.
Let me know if LiveList makes further problems in your code.

**Comment by RodrigoSMarques** [comment]
HI @maaeps 
I'm going to do a test.

**Pull request merged**
