### PR TITLE
Release/2.0.1

### PR DESCRIPTION
**Pull request by fischerscode**
Changelog:
## 2.0.1
Fixed network exceptions. [#482](https://github.com/parse-community/Parse-SDK-Flutter/pull/482)

### CODE REVIEW

**Comment by fischerscode** [comment]
@phillwiggins 
Sorry for all the @mentions recently.
I propose this release, as 2.0.0 unfortunately introduced a bug, where network exceptions where not handled correctly.
This release would fix #481 as well as #484 and has also been proposed by @RodrigoSMarques.

(The tests fail `Because parse_server_sdk_flutter depends on parse_server_sdk ^2.0.1 which doesn't match any versions, version solving failed.`)

**Comment by RodrigoSMarques** [comment]
@phillwiggins / @fischerscode 
Good afternoon!
Can you release this fix? I am in contact with other developers and all of them reporting the same problem.

**Comment by fischerscode** [comment]
@RodrigoSMarques 
I have no access to the pub.dev site.
Only @phillwiggins can release a new version.

**Comment by phillwiggins** [comment]
Apologies, I didn't see this.

I will release this in the next 24 hours hopefully.

**Comment by fischerscode** [comment]
@phillwiggins 
Well, as I always say, it's opensource, no time pressure. :-D

**Comment by fischerscode** [comment]
I've just created a github release. I forgot to do it earlier.

**Pull request merged**
