### PR TITLE
refactor: Remove deprecated property `window` from `dart:ui` in favor of `PlatformDispatcher`

### PR DESCRIPTION
**Pull request by Nidal-Bakir**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description

Closes: #877

### Approach

Use the PlatformDispatcher class as recommended by the Flutter docs see [window class docs](https://api.flutter.dev/flutter/dart-ui/window.html)

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [ ] A changelog entry

### CODE REVIEW

**Review by mbfakourii — APPROVED** [review]

**Comment by mtrezza** [comment]
Is this a breaking change or only an internal refactor?

**Comment by Nidal-Bakir** [comment]
Internal refactor the developers will not notice it

**Comment by mtrezza** [comment]
Alright, so we also don't need a changelog entry for it. All looks green - yay! - can we merge this?

**Comment by Nidal-Bakir** [comment]
sure, we can!!!!!!!! finally :)

**Comment by mtrezza** [comment]
Is this the last breaking change for the Parse Flutter SDK? If so, we could release Flutter 5.0.0 with this PR.

- Why do we need https://github.com/parse-community/Parse-SDK-Flutter/pull/868 if all checks are green in this PR already?
- The Dart SDK has a version constant `const String keySdkVersion = '5.0.0';` in `parse_constants.dart` that needs to be kept in sync manually with the version in `pubspec.yaml`. Does the Flutter SDK have something similar?

**Comment by Nidal-Bakir** [comment]
>Why do we need https://github.com/parse-community/Parse-SDK-Flutter/pull/868 if all checks are green in this PR already? That would be another breaking change we'd probably have to include before a Flutter 5 release.

But then if anyone uses Flutter SDK will be locked to Dart SDK 4.x.x

>The Dart SDK has a version constant const String keySdkVersion = '5.0.0'; in parse_constants.dart that needs to be kept in sync manually with the version in pubspec.yaml. Does the Flutter SDK have something similar?

No, there is nothing like that in the Flutter SDK

**Comment by mtrezza** [comment]
> But then if anyone uses Flutter SDK will be locked to Dart SDK 4.x.x.

Could we instead just say `>=4.0.0 <6.0.0` in #868?

**Pull request merged**
