### PR TITLE
refactor: Add pubspec in dart example

### PR DESCRIPTION
**Pull request by mbfakourii**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/Parse-SDK-Flutter/blob/master/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

## Issue
add pubspec in dart example and fix main.dart example warning

Closes: #905

## Approach
n/a

## Tasks
n/a

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)

### CODE REVIEW

**Comment by mtrezza** [comment]
It's a fix in the example, which is not part of the SDK itself, so this is merely a `refactor`.

**Review by mtrezza — APPROVED** [review]
Looks good, ready for merge?

**Comment by mbfakourii** [comment]
> Looks good, ready for merge?

Yes, I think it is ready

**Review by Nidal-Bakir — APPROVED** [review]

**Comment by Nidal-Bakir** [comment]
I just tested it with `dart analyze packages/dart --fatal-infos` no issues were found. We are good to publish Dart 5.1.1

**Comment by Nidal-Bakir** [comment]
See https://github.com/parse-community/Parse-SDK-Flutter/pull/906#issuecomment-1554221396

**Comment by mtrezza** [comment]
Can this PR be merged despite the failing CI?

**Comment by mbfakourii** [comment]
> Can this PR be merged despite the failing CI?

This error is related to the version of Flutter, merge it and there will be no problem

**Review by mtrezza — APPROVED** [review]

**Pull request merged**
