### PR TITLE
Updated Live Queries related documentation

### PR DESCRIPTION
**Pull request by mregandla**
Current documentation has deprecated methods usage.

### CODE REVIEW

**Comment by phillwiggins** [comment]
Hey, please can you close this MR and create a new one that will be merged into the branch release/1.0.26.

Thanks in advance!

**Comment by WahdanZ** [comment]
It there an option to subscribe to all events

**Comment by mregandla** [comment]
@WahdanZ We don't have an option to subscribe to all events at once. You may write a utility function.

**Comment by mregandla** [comment]
Closing this and follow this new PR: https://github.com/parse-community/Parse-SDK-Flutter/pull/301

**Pull request closed without merging**
