### PR TITLE
refactor: Bump flutter version to `3.1.4`

### PR DESCRIPTION
**Pull request by mbfakourii**
### New Pull Request Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description
bump flutter version to ```3.1.4```

Closes: #816

### Approach
n/a

### TODOs before merging
- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry

### CODE REVIEW

**Comment by mtrezza** [comment]
Why do we need this?

**Comment by mbfakourii** [comment]
> Why do we need this?

If we use the Flutter package, we do not have the latest version of the Dart package

**Comment by mbfakourii** [comment]
> Why do we need this?

If we use the Flutter package, we do not have the latest version of the Dart package

**Comment by mtrezza** [comment]
I think this PR can be closed, see https://github.com/parse-community/Parse-SDK-Flutter/issues/816#issuecomment-1365350371

**Pull request closed without merging**
