### PR TITLE
feat: Add `ParseObject.toJson()` to create a JSON representation

### PR DESCRIPTION
**Pull request by mbfakourii**
### New Pull Request Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-Flutter/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/Parse-SDK-Flutter/issues?q=is%3Aissue).

### Issue Description
remove protected in ```toJson``` for use externally

Closes: #616

### Approach
only remove protected in ```toJson```

### TODOs before merging
- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry

### CODE REVIEW

**Comment by mtrezza** [comment]
I've changed the commit type to `feat`, since from the developer perspective it's a new method the SDK offers.

Does the PR title make sense?

**Comment by mbfakourii** [comment]
> I've changed the commit type to `feat`, since from the developer perspective it's a new method the SDK offers.
> 
> Does the PR title make sense?

Yes, this title looks better

**Comment by mbfakourii** [comment]
> Alright, if you want to add a changelog entry and bump the version we can release.

added

**Review by mtrezza — APPROVED** [review]
Looks good!

**Pull request merged**
